site_name: "Semaphore Mobile — React Native"
site_url: "https://docs.semaphoremobile.com/react-native/"
theme:
  name: material
  logo: img/shared/sema-red-logo.png
  favicon: img/shared/sema-red-logo.png  
  features:
    - navigation.sections
    - search.suggest
nav:
  - Overview: index.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
extra_css:
  - styles/extra.css
