name: Deploy Docs
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs + plugins
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build all
        run: bash scripts/build_all.sh

      - name: Set up Ruby (Capistrano)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install Capistrano deps
        run: bundle install --path vendor/bundle

      - name: SSH keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Known hosts
        run: ssh-keyscan -t rsa docs.semaphoremobile.com >> ~/.ssh/known_hosts

      - name: Deploy
        run: bundle exec cap production deploy
